import { StyleSheet } from "react-native";

import { theme } from "./theme";

const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  content: {
    paddingBottom: theme.spacing.xlarge * 2,
  },
  hero: {
    height: 220,
    justifyContent: "flex-end",
  },
  heroImage: {
    opacity: 0.7,
  },
  heroOverlay: {
    backgroundColor: "rgba(5,5,15,0.75)",
    paddingHorizontal: theme.spacing.large,
    paddingVertical: theme.spacing.large,
  },
  welcomeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  heroTitle: {
    color: theme.colors.primary,
    fontSize: theme.typography.sizes.xlarge,
    fontWeight: theme.typography.weights.bold,
  },
  heroSubtitle: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.small,
    marginTop: theme.spacing.xsmall,
  },
  heroAvatar: {
    width: 56,
    height: 56,
    borderRadius: theme.radius.round,
    borderWidth: 2,
    borderColor: theme.colors.primary,
  },
  section: {
    paddingHorizontal: theme.spacing.large,
    marginTop: theme.spacing.xlarge,
  },
  sectionHeader: {
    marginBottom: theme.spacing.medium,
  },
  sectionTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.large,
    fontWeight: theme.typography.weights.bold,
  },
  sectionSubtitle: {
    color: theme.colors.textSubtle,
    fontSize: theme.typography.sizes.small,
    marginTop: theme.spacing.xsmall,
  },
  mixCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.large,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.large,
    marginTop: theme.spacing.medium,
  },
  mixHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: theme.spacing.small,
  },
  mixTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.medium,
    fontWeight: theme.typography.weights.medium,
  },
  shuffleButton: {
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    borderColor: theme.colors.primary,
    paddingHorizontal: theme.spacing.medium,
    paddingVertical: theme.spacing.xsmall,
  },
  shuffleText: {
    color: theme.colors.primary,
    fontSize: theme.typography.sizes.small,
    fontWeight: theme.typography.weights.medium,
  },
  mixHeadline: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.large,
    fontWeight: theme.typography.weights.bold,
    marginBottom: theme.spacing.xsmall,
  },
  mixBlurb: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.sizes.small,
    marginBottom: theme.spacing.small,
    lineHeight: theme.typography.sizes.small + 4,
  },
  mixQuote: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.medium,
    lineHeight: theme.typography.sizes.medium + 8,
    marginBottom: theme.spacing.small,
  },
  mixSource: {
    color: theme.colors.textSubtle,
    fontSize: theme.typography.sizes.small,
  },
  traitRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: theme.spacing.small,
  },
  traitBadge: {
    backgroundColor: "rgba(252,191,73,0.18)",
    borderRadius: theme.radius.pill,
    paddingHorizontal: theme.spacing.small,
    paddingVertical: theme.spacing.xsmall,
    marginRight: theme.spacing.small,
    marginBottom: theme.spacing.small,
  },
  traitText: {
    color: theme.colors.primary,
    fontSize: theme.typography.sizes.small - 1,
    fontWeight: theme.typography.weights.medium,
  },
  spotlightCard: {
    flexDirection: "row",
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.large,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.medium,
    marginTop: theme.spacing.medium,
  },
  spotlightPoster: {
    width: 120,
    height: 180,
    borderRadius: theme.radius.medium,
    marginRight: theme.spacing.medium,
  },
  spotlightDetails: {
    flex: 1,
    justifyContent: "space-between",
  },
  spotlightTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.medium,
    fontWeight: theme.typography.weights.bold,
    marginBottom: theme.spacing.small,
  },
  spotlightMeta: {
    color: theme.colors.textSubtle,
    fontSize: theme.typography.sizes.small,
    marginBottom: theme.spacing.small,
  },
  spotlightButton: {
    marginTop: theme.spacing.small,
    alignSelf: "flex-start",
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radius.pill,
    paddingHorizontal: theme.spacing.large,
    paddingVertical: theme.spacing.small,
  },
  spotlightButtonText: {
    color: theme.colors.background,
    fontSize: theme.typography.sizes.small,
    fontWeight: theme.typography.weights.medium,
  },
  carouselContent: {
    paddingRight: theme.spacing.large,
  },
  carouselCard: {
    width: 180,
    marginRight: theme.spacing.medium,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.large,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.medium,
  },
  carouselPoster: {
    width: "100%",
    height: 200,
    borderRadius: theme.radius.medium,
    marginBottom: theme.spacing.small,
  },
  carouselTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.small,
    fontWeight: theme.typography.weights.medium,
    marginBottom: theme.spacing.xsmall,
  },
  carouselMeta: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.sizes.small - 1,
    marginTop: theme.spacing.xsmall,
  },
  progressTrack: {
    marginTop: theme.spacing.small,
    height: 6,
    borderRadius: theme.radius.pill,
    backgroundColor: "rgba(255,255,255,0.12)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: theme.colors.secondary,
    borderRadius: theme.radius.pill,
  },
  quickGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  quickTile: {
    width: "48%",
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.medium,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.medium,
    marginBottom: theme.spacing.medium,
  },
  quickLabel: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.small,
    fontWeight: theme.typography.weights.bold,
    marginBottom: theme.spacing.xsmall,
  },
  quickDescription: {
    color: theme.colors.textSubtle,
    fontSize: theme.typography.sizes.small - 1,
    lineHeight: theme.typography.sizes.small + 2,
  },
  activityChart: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.large,
    borderWidth: 1,
    borderColor: theme.colors.border,
    paddingHorizontal: theme.spacing.medium,
    paddingTop: theme.spacing.large,
    paddingBottom: theme.spacing.medium,
  },
  activityColumn: {
    alignItems: "center",
    width: 26,
  },
  activityBarShell: {
    width: 16,
    height: 90,
    borderRadius: theme.radius.pill,
    backgroundColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
    justifyContent: "flex-end",
  },
  activityBarFill: {
    width: "100%",
    backgroundColor: theme.colors.accent,
    borderRadius: theme.radius.pill,
  },
  activityLabel: {
    color: theme.colors.textSubtle,
    fontSize: theme.typography.sizes.small - 1,
    marginTop: theme.spacing.xsmall,
  },
  communityCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.large,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.large,
    marginTop: theme.spacing.medium,
  },
  communityTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.medium,
    fontWeight: theme.typography.weights.bold,
    marginBottom: theme.spacing.small,
  },
  communitySummary: {
    color: theme.colors.textSubtle,
    fontSize: theme.typography.sizes.small,
    lineHeight: theme.typography.sizes.small + 4,
    marginBottom: theme.spacing.medium,
  },
  communityButton: {
    alignSelf: "flex-start",
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    borderColor: theme.colors.primary,
    paddingHorizontal: theme.spacing.large,
    paddingVertical: theme.spacing.small,
  },
  communityButtonText: {
    color: theme.colors.primary,
    fontSize: theme.typography.sizes.small,
    fontWeight: theme.typography.weights.medium,
  },
});

export default homeStyles;
