import { StyleSheet } from "react-native";

import { theme } from "./theme";

const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  content: {
    paddingBottom: theme.spacing.xlarge * 2,
  },
  banner: {
    height: 180,
    justifyContent: "flex-end",
    marginBottom: -(theme.spacing.large + theme.spacing.medium),
  },
  bannerImage: {
    opacity: 0.6,
  },
  bannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(11,11,15,0.45)",
  },
  bannerCta: {
    alignSelf: "flex-end",
    backgroundColor: "rgba(0,0,0,0.45)",
    paddingHorizontal: theme.spacing.medium,
    paddingVertical: theme.spacing.xsmall,
    borderRadius: theme.radius.pill,
    margin: theme.spacing.medium,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  bannerCtaText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.sizes.small,
  },
  header: {
    alignItems: "center",
    paddingHorizontal: theme.spacing.large,
    paddingTop: theme.spacing.xlarge + theme.spacing.small,
    paddingBottom: theme.spacing.large,
  },
  avatarRing: {
    padding: 4,
    borderRadius: theme.radius.round,
    backgroundColor: "rgba(5,5,15,0.9)",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.18)",
    marginBottom: theme.spacing.small,
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: theme.radius.round,
  },
  username: {
    fontSize: theme.typography.sizes.xlarge,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.primary,
    marginTop: theme.spacing.small,
  },
  bio: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.small,
    textAlign: "center",
    marginTop: theme.spacing.xsmall,
    lineHeight: theme.typography.sizes.small + 6,
  },
  email: {
    color: theme.colors.textSubtle,
    fontSize: theme.typography.sizes.small,
    marginTop: theme.spacing.xsmall,
    textAlign: "center",
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: theme.spacing.medium,
  },
  tagChip: {
    paddingHorizontal: theme.spacing.small,
    paddingVertical: theme.spacing.xsmall,
    borderRadius: theme.radius.pill,
    backgroundColor: "rgba(255,255,255,0.08)",
    marginHorizontal: theme.spacing.xsmall,
    marginBottom: theme.spacing.xsmall,
  },
  tagText: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.small - 1,
  },
  section: {
    paddingHorizontal: theme.spacing.large,
    marginBottom: theme.spacing.xlarge,
  },
  sectionTitle: {
    fontSize: theme.typography.sizes.large,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.primary,
  },
  sectionSubtitle: {
    color: theme.colors.textSubtle,
    fontSize: theme.typography.sizes.small,
    marginTop: theme.spacing.xsmall,
    marginBottom: theme.spacing.medium,
    lineHeight: theme.typography.sizes.small + 4,
  },
  statGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  statCard: {
    width: "48%",
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.medium,
    padding: theme.spacing.medium,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: theme.spacing.medium,
  },
  statCardLabel: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.sizes.small,
  },
  statCardValue: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.large,
    fontWeight: theme.typography.weights.bold,
    marginTop: theme.spacing.xsmall,
  },
  statCardSub: {
    color: theme.colors.textSubtle,
    fontSize: theme.typography.sizes.small,
    marginTop: theme.spacing.xsmall,
  },
  genreCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: theme.radius.medium,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.medium,
    marginBottom: theme.spacing.medium,
  },
  genreTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.medium,
    fontWeight: theme.typography.weights.medium,
    marginBottom: theme.spacing.small,
  },
  genreRow: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  genreChip: {
    paddingHorizontal: theme.spacing.small,
    paddingVertical: theme.spacing.xsmall,
    borderRadius: theme.radius.pill,
    backgroundColor: "rgba(252,191,73,0.2)",
    marginRight: theme.spacing.small,
    marginBottom: theme.spacing.small,
  },
  genreText: {
    color: theme.colors.primary,
    fontSize: theme.typography.sizes.small,
    fontWeight: theme.typography.weights.medium,
  },
  pieSection: {
    marginTop: theme.spacing.medium,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.medium,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.medium,
  },
  pieContainer: {
    alignItems: "center",
  },
  pieChart: {
    width: 160,
    height: 160,
    borderRadius: 80,
    borderWidth: 24,
    borderColor: "rgba(255,255,255,0.12)",
    marginBottom: theme.spacing.medium,
  },
  pieCenter: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  pieTotal: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.large,
    fontWeight: theme.typography.weights.bold,
  },
  pieLabel: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.sizes.small,
    marginTop: 2,
  },
  legendList: {
    width: "100%",
  },
  legendRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: theme.spacing.xsmall,
  },
  legendDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: theme.spacing.small,
  },
  legendLabel: {
    flex: 1,
    color: theme.colors.text,
    fontSize: theme.typography.sizes.small,
  },
  legendValue: {
    color: theme.colors.textSubtle,
    fontSize: theme.typography.sizes.small,
  },
  achievementScroller: {
    paddingRight: theme.spacing.large,
  },
  achievementCard: {
    width: 210,
    padding: theme.spacing.medium,
    borderRadius: theme.radius.medium,
    borderWidth: 1,
    marginRight: theme.spacing.medium,
  },
  achievementUnlocked: {
    borderColor: theme.colors.primary,
    backgroundColor: "rgba(252,191,73,0.18)",
  },
  achievementLocked: {
    borderColor: theme.colors.border,
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  achievementTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.medium,
    fontWeight: theme.typography.weights.bold,
    marginBottom: theme.spacing.small,
  },
  achievementDetail: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.small,
    lineHeight: theme.typography.sizes.small + 4,
    marginBottom: theme.spacing.small,
  },
  achievementMeta: {
    color: theme.colors.textSubtle,
    fontSize: theme.typography.sizes.small - 1,
  },
  favoriteScroller: {
    paddingRight: theme.spacing.large,
  },
  favoriteCard: {
    width: 150,
    borderRadius: theme.radius.medium,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.small,
    marginRight: theme.spacing.medium,
  },
  favoritePoster: {
    width: "100%",
    height: 190,
    borderRadius: theme.radius.small,
    marginBottom: theme.spacing.small,
  },
  favoriteTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.small,
    fontWeight: theme.typography.weights.medium,
    marginBottom: theme.spacing.xsmall,
  },
  favoriteNote: {
    color: theme.colors.textSubtle,
    fontSize: theme.typography.sizes.small - 1,
    lineHeight: theme.typography.sizes.small + 2,
  },
  activityCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.medium,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.small,
  },
  activityRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: theme.spacing.small,
    paddingHorizontal: theme.spacing.small,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.04)",
  },
  activityIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    marginRight: theme.spacing.medium,
  },
  activityCopy: {
    flex: 1,
  },
  activityDescription: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.small,
    lineHeight: theme.typography.sizes.small + 4,
  },
  activityTime: {
    color: theme.colors.textSubtle,
    fontSize: theme.typography.sizes.small - 1,
    marginTop: 2,
  },
  settingsPanel: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.medium,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.medium,
  },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: theme.spacing.medium,
  },
  settingCopy: {
    flex: 1,
    marginRight: theme.spacing.medium,
  },
  settingLabel: {
    color: theme.colors.text,
    fontSize: theme.typography.sizes.small,
    fontWeight: theme.typography.weights.medium,
  },
  settingDescription: {
    color: theme.colors.textSubtle,
    fontSize: theme.typography.sizes.small - 1,
    marginTop: theme.spacing.xsmall,
    lineHeight: theme.typography.sizes.small + 2,
  },
  linkButton: {
    marginTop: theme.spacing.small,
    paddingVertical: theme.spacing.small,
  },
  linkButtonText: {
    color: theme.colors.secondary,
    fontSize: theme.typography.sizes.small,
    fontWeight: theme.typography.weights.medium,
  },
  logoutButton: {
    backgroundColor: theme.colors.danger,
    padding: theme.spacing.medium,
    borderRadius: theme.radius.medium,
    alignItems: "center",
    marginHorizontal: theme.spacing.large,
    marginBottom: theme.spacing.xlarge,
  },
  logoutButtonDisabled: {
    opacity: 0.4,
  },
  logoutText: {
    fontSize: theme.typography.sizes.medium,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.text,
  },
});

export default profileStyles;
